# Generated by Django 5.2 on 2025-04-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SurveySubmission',
        ),
    ]
